### ISSUE TITLE
Add a NotifyWorkflow to alert on fail or success status 

### ISSUE THREAD

**Issue by qgeffard** [qgeffard/getmyfreeweeklygame#2]

**Comment by qgeffard** [comment]
@leghort please do it soon

**Comment by qgeffard** [comment]
#1  @leghort what is this shit ??

**Comment by medaey** [comment]
Use that
https://github.com/Discord4J/Discord4J

**Comment by medaey** [comment]
@qgeffard It's okay, right?
https://github.com/qgeffard/getmyfreeweeklygame/commits/master
